CREATE DATABASE IF NOT EXISTS ETL_JOY;

USE ETL_JOY;

CREATE TABLE IF NOT EXISTS broadcasts (
    painting_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    painting_title INT NOT NULL,
    season INT NOT NULL,
    EPISODE INT NOT NULL
);

CREATE TABLE IF NOT EXISTS subject_matter (
    episode VARCHAR(255) NOT NULL PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    attribute INT NOT NULL
);

CREATE TABLE IF NOT EXISTS colors (
    color_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    color_name VARCHAR(255) NOT NULL,
    color_hex INT NOT NULL
);
